# Default Configurations 
defaults:
  - communication: baseline_mimo_dct
  - dataset: cifar_100
  - model: deit_tiny_patch16_224
  - optimizer: adam
  - method : gumbel
  - hydra: default
  - _self_

# Hyperparameters 
hyperparameters:
  split_index : 1  # Where to split the network
  experiment_name : test  # Name of the experiment
  seeds: [42]  # Single seed by default for faster turnaround

# Set folders for results, datasets and plots 
core:
  dataset_path: ./data
  results_path: ./results
  plots_path : ./plots

hydra:
  run:
    # Hydra salverà i suoi file (.hydra/) in questa cartella dedicata
    dir: ${core.results_path}/hydra_runs/${hyperparameters.experiment_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  
  output_subdir: .hydra  # Crea la sottocartella .hydra all'interno della 'dir' sopra
  
  job:
    chdir: false  # IMPORTANTE: false (non No) mantiene la working directory originale
  
  job_logging:
    root:
      level: WARNING